const $=id=>document.getElementById(id);
const grid=$('grid'),tabs=$('tabs'),rank=$('rank'),statusEl=$('status'),quick=$('quick'),q=$('q'),sort=$('sort'),featured=$('featured');
let items=[],current='all';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const when=iso=>{const d=new Date(iso);return isNaN(d)?'-':new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)};
const source=x=>typeof x?.source==='string'?x.source:(x?.source?.name||'원문');
function flatten(p){let a=[];if(Array.isArray(p?.allItems))a=p.allItems;else if(Array.isArray(p?.items))a=p.items;else if(Array.isArray(p?.posts))a=p.posts;else if(Array.isArray(p?.news))a=p.news;else if(p?.byCategory&&typeof p.byCategory==='object')a=Object.values(p.byCategory).flat();return a.filter(x=>x&&x.title&&(x.url||x.link)).map((x,i)=>({id:x.id||`item-${i}`,category:x.category||x.theme||'news',categoryName:x.categoryName||x.category_ko||x.themeName||x.theme||x.category||'뉴스',categoryIcon:x.categoryIcon||x.icon||'📰',title:x.title,description:x.description||x.summary||x.contentSnippet||'원문에서 전체 내용을 확인하세요.',url:x.url||x.link,source:typeof x.source==='string'?{name:x.source}:x.source||{name:'원문'},publishedAt:x.publishedAt||x.published_at||x.pubDate||x.date||p?.generatedAt,score:Number(x.score||x.priority||x.hotScore||0),tags:Array.isArray(x.tags)?x.tags:[]}));}
function merge(ps){const seen=new Set(),out=[];for(const p of ps){for(const x of flatten(p)){const key=(x.url||'').trim()||`${x.title}|${source(x)}`.toLowerCase();if(seen.has(key))continue;seen.add(key);out.push(x);}}return out;}
function cats(){const map=new Map(),meta={};for(const x of items){map.set(x.category,(map.get(x.category)||0)+1);meta[x.category]=[x.categoryName,x.categoryIcon];}return [...map].map(([id,count])=>({id,count,name:meta[id]?.[0]||id,icon:meta[id]?.[1]||'📰'})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'ko'));}
function sorted(){const a=[...items];return sort.value==='latest'?a.sort((x,y)=>new Date(y.publishedAt)-new Date(x.publishedAt)||(y.score||0)-(x.score||0)):a.sort((x,y)=>(y.score||0)-(x.score||0)||new Date(y.publishedAt)-new Date(x.publishedAt));}
function filtered(){const t=q.value.trim().toLowerCase();return sorted().filter(x=>(current==='all'||x.category===current||x.categoryName===current)&&(!t||(x.title+' '+x.description+' '+source(x)+' '+x.tags.join(' ')).toLowerCase().includes(t)));}
function newest(){return items.map(x=>new Date(x.publishedAt)).filter(d=>!isNaN(d)).sort((a,b)=>b-a)[0];}
function card(x){const icon=esc(x.categoryIcon||'📰');return `<article class="card"><div><div class="meta"><span class="chip">${icon} ${esc(x.categoryName)}</span><span class="score">HOT ${esc(x.score)}</span></div><h2><a target="_blank" rel="noopener noreferrer" href="${esc(x.url)}">${esc(x.title)}</a></h2><p>${esc(x.description)}</p><footer><span>${esc(source(x))}</span><time>${esc(when(x.publishedAt))}</time></footer></div><a class="thumb" target="_blank" rel="noopener noreferrer" href="${esc(x.url)}">${icon}</a></article>`;}
function feature(){const top=sorted()[0];const stat=`<div class="stats"><div class="stat"><span>상태</span><b>${items.length?'정상':'대기'}</b></div><div class="stat"><span>기사</span><b>${items.length}</b></div><div class="stat"><span>테마</span><b>${cats().length}</b></div><div class="stat"><span>갱신</span><b>${esc(when(newest()))}</b></div></div>`;featured.innerHTML=top?`<div><span class="badge">🔥 TOP HEADLINE</span><h2><a target="_blank" rel="noopener noreferrer" href="${esc(top.url)}">${esc(top.title)}</a></h2><p>${esc(top.description)}</p><div class="fmeta"><span>${esc(source(top))}</span><span>${esc(top.categoryIcon)} ${esc(top.categoryName)}</span><time>${esc(when(top.publishedAt))}</time></div></div>${stat}`:`<div><span class="badge">NEWS</span><h2>표시할 뉴스가 없습니다</h2><p>데이터를 다시 불러오세요.</p></div>${stat}`;}
function render(){const arr=filtered();grid.innerHTML=arr.length?arr.map(card).join(''):'<article class="card error"><div><h2>표시할 뉴스가 없습니다</h2><p>검색어 또는 테마를 바꿔보세요.</p></div></article>';const msg=`현재 ${arr.length}개 표시 · 전체 ${items.length}개`;statusEl.textContent=msg;quick.textContent=msg;feature();}
function draw(ps){items=merge(ps);current='all';const cs=cats();rank.innerHTML=sorted().slice(0,8).map((x,i)=>`<li><b>${i+1}</b><a target="_blank" rel="noopener noreferrer" href="${esc(x.url)}">${esc(x.title)}</a></li>`).join('')||'<li><b>!</b><span>뉴스 없음</span></li>';tabs.innerHTML=`<button class="tab active" data-id="all">전체 ${items.length}</button>`+cs.map(c=>`<button class="tab" data-id="${esc(c.id)}">${esc(c.icon)} ${esc(c.name)} ${c.count}</button>`).join('');tabs.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{tabs.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.id;render();});render();}
async function getJson(path,required=false){const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok){if(required)throw new Error(`${path} HTTP ${r.status}`);return null;}return r.json();}
async function load(){quick.textContent='뉴스 데이터 연결 중입니다.';statusEl.textContent='뉴스 데이터 연결 중입니다.';grid.innerHTML='<article class="card"><div><h2>뉴스 데이터 연결 중</h2><p>잠시 후 목록이 표시됩니다.</p></div></article>';try{const [latest,base]=await Promise.all([getJson('./latest.json'),getJson('./data.json',true)]);draw([latest,base].filter(Boolean));}catch(e){quick.textContent='데이터 연결 실패';statusEl.textContent='데이터 연결 실패: '+e.message;featured.innerHTML='<div><span class="badge">ERROR</span><h2>뉴스 데이터 연결 실패</h2><p>다시 읽기를 누르거나 data.json 파일을 확인하세요.</p></div><div class="stats"><div class="stat"><span>상태</span><b>실패</b></div><div class="stat"><span>기사</span><b>-</b></div><div class="stat"><span>테마</span><b>-</b></div><div class="stat"><span>갱신</span><b>-</b></div></div>';grid.innerHTML='<article class="card error"><div><h2>뉴스 데이터 연결 실패</h2><p>다시 읽기를 누르거나 RSS로 이동하세요.</p></div></article>';rank.innerHTML='<li><b>!</b><span>데이터 연결 실패</span></li>';}}
q.oninput=render;sort.onchange=render;$('searchBtn').onclick=render;$('retry').onclick=load;$('retryTop').onclick=load;load();
