(()=>{
const SOURCES=['./latest-20260614-1908.json','./latest-20260614-1850.json','./latest-20260614-1408.json','./latest-20260613-2135.json','./latest.json','./data.json'];
const $=s=>document.querySelector(s),grid=$('#grid'),tabs=$('#tabs'),q=$('#q'),sort=$('#sort'),state=$('#state'),rank=$('#rank');
let items=[],current='all';
const src=x=>typeof x.source==='object'?(x.source.name||'원문'):(x.source||'원문');
const dv=x=>x.publishedAt||x.date||x.published_at||x.pubDate||'';
const sc=x=>Number(x.score??x.priority??x.hotScore??0)||0;
const when=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'-':d.toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})};
const safe=v=>{try{const u=new URL(v,location.href);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}};
function flatten(p){if(!p)return[];const r=[];['allItems','items','posts','news'].forEach(k=>Array.isArray(p[k])&&r.push(...p[k]));if(p.byCategory&&typeof p.byCategory==='object')Object.values(p.byCategory).forEach(v=>Array.isArray(v)&&v.forEach(y=>{if(y&&typeof y==='object')r.push(y)}));return r}
function norm(x,i){return{id:x.id||`news-${i}`,category:x.category||x.theme||'news',categoryName:x.categoryName||x.category_ko||x.themeName||x.theme||x.category||'뉴스',categoryIcon:x.categoryIcon||x.icon||'📰',title:x.title||x.name||'',description:x.description||x.summary||x.contentSnippet||'',url:x.url||x.link||'',source:x.source||'원문',publishedAt:dv(x),score:sc(x),tags:Array.isArray(x.tags)?x.tags:[]}}
function dedupe(a){const u=new Set,t=new Set,o=[];a.map(norm).forEach(x=>{if(!x.title||!x.url)return;const U=x.url.toLowerCase().replace(/\/$/,''),T=(x.title+'|'+src(x)).toLowerCase().replace(/\s+/g,' ');if(u.has(U)||t.has(T))return;u.add(U);t.add(T);o.push(x)});return o}
function link(h,text){const a=document.createElement('a');a.href=safe(h);a.target='_blank';a.rel='noopener noreferrer';a.textContent=text;return a}
function card(x){const a=document.createElement('article');a.className='card';const m=document.createElement('div');m.className='meta';const c=document.createElement('span');c.textContent=`${x.categoryIcon} ${x.categoryName}`;const b=document.createElement('b');b.textContent=`HOT ${x.score}`;m.append(c,b);const h=document.createElement('h2');h.append(link(x.url,x.title));const p=document.createElement('p');p.className='muted';p.textContent=x.description||'요약 없음';const f=document.createElement('p');f.className='muted';f.textContent=`${src(x)} · ${when(x.publishedAt)}`;a.append(m,h,p,f);return a}
function sorted(){return [...items].sort(sort.value==='latest'?(a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)||b.score-a.score:(a,b)=>b.score-a.score||new Date(b.publishedAt)-new Date(a.publishedAt))}
function renderRank(){rank.replaceChildren();sorted().slice(0,10).forEach((x,i)=>{const li=document.createElement('li'),n=document.createElement('b'),body=document.createElement('span'),meta=document.createElement('small');n.textContent=String(i+1);meta.textContent=`${src(x)} · HOT ${x.score} · ${x.categoryName}`;body.append(link(x.url,x.title),meta);li.append(n,body);rank.append(li)});if(!rank.children.length){const li=document.createElement('li');li.textContent='뉴스 없음';rank.append(li)}}
function renderTabs(){tabs.replaceChildren();const all=document.createElement('button');all.type='button';all.className='tab on';all.dataset.category='all';all.textContent=`전체 ${items.length}`;tabs.append(all);const cnt=new Map(),lab=new Map();items.forEach(x=>{cnt.set(x.category,(cnt.get(x.category)||0)+1);lab.set(x.category,`${x.categoryIcon} ${x.categoryName}`)});[...cnt].sort((a,b)=>b[1]-a[1]).forEach(([c,n])=>{const bt=document.createElement('button');bt.type='button';bt.className='tab';bt.dataset.category=c;bt.textContent=`${lab.get(c)||c} ${n}`;tabs.append(bt)})}
function render(){const query=q.value.toLowerCase().trim();const list=sorted().filter(x=>{const h=`${x.title} ${x.description} ${src(x)} ${x.tags.join(' ')}`.toLowerCase();return(current==='all'||x.category===current)&&(!query||h.includes(query))});grid.replaceChildren();list.length?list.forEach(x=>grid.append(card(x))):(grid.innerHTML='<article class="card empty">표시할 뉴스 없음</article>');state.textContent=`표시 ${list.length} / 전체 ${items.length} · 인기뉴스 ${Math.min(10,items.length)}위까지 표시`;renderRank()}
async function get(p){try{const r=await fetch(`${p}?v=${Date.now()}`,{cache:'no-store'});return r.ok?r.json():null}catch{return null}}
async function load(){state.textContent='뉴스 데이터 연결 중';grid.textContent='뉴스 데이터 연결 중';rank.innerHTML='<li><b>·</b><span>순위 계산 중</span></li>';const ps=await Promise.all(SOURCES.map(get));items=dedupe(ps.flatMap(flatten));current='all';renderTabs();render()}
q.addEventListener('input',render);sort.addEventListener('change',render);$('#reload').addEventListener('click',load);tabs.addEventListener('click',e=>{const b=e.target.closest('.tab');if(!b)return;current=b.dataset.category;tabs.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');render()});load();
})();